# Generated by Django 5.0.6 on 2026-02-06 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(blank=True, max_length=64)),
                ('discord_id', models.CharField(blank=True, max_length=64)),
                ('bio', models.TextField(blank=True)),
                ('reputation_score', models.IntegerField(default=0)),
                ('main_game', models.CharField(choices=[('cs2', 'Counter-Strike 2'), ('dota2', 'Dota 2'), ('valorant', 'Valorant')], default='cs2', max_length=16)),
                ('rank', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
