# Generated by Django 5.0.6 on 2026-02-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_and_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
