# Generated by Django 5.0.6 on 2026-02-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_gamerprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerprofile',
            name='avatar',
        ),
    ]
