# Generated by Django 5.0.6 on 2026-03-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerprofile',
            name='main_game',
        ),
    ]
