# Generated by Django 5.0.6 on 2026-03-13 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0010_tournament_image'),
        ('users', '0008_remove_gamerprofile_main_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='main_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gamers', to='lobbies.game'),
        ),
    ]
