# Generated by Django 5.0.6 on 2026-03-20 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_gamerprofile_main_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='cs2_faceit_elo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Faceit ELO'),
        ),
        migrations.AlterField(
            model_name='gamerprofile',
            name='cs2_faceit_lvl',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
