# Generated by Django 5.0.6 on 2026-02-06 06:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('game', models.CharField(choices=[('cs2', 'Counter-Strike 2'), ('dota2', 'Dota 2'), ('valorant', 'Valorant')], default='cs2', max_length=16)),
                ('required_rank', models.CharField(choices=[('any', 'Any'), ('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], default='any', max_length=16)),
                ('mic_required', models.BooleanField(default=False)),
                ('slots_total', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('slots_filled', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('full', 'Full'), ('ended', 'Ended')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_lobbies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LobbyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lobbies.lobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='lobby',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('host',), name='uniq_active_lobby_per_host'),
        ),
        migrations.AddConstraint(
            model_name='lobbyparticipant',
            constraint=models.UniqueConstraint(fields=('lobby', 'user'), name='uniq_lobby_participant'),
        ),
    ]
