# Generated by Django 5.0.6 on 2026-02-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lobby',
            name='req_cs2_faceit_lvl',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='req_cs2_premier_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='req_dota2_rank',
            field=models.CharField(choices=[('any', 'Any'), ('herald', 'Herald'), ('guardian', 'Guardian'), ('crusader', 'Crusader'), ('archon', 'Archon'), ('legend', 'Legend'), ('ancient', 'Ancient'), ('divine', 'Divine'), ('immortal', 'Immortal')], default='any', max_length=16),
        ),
        migrations.AddField(
            model_name='lobby',
            name='req_valorant_rank',
            field=models.CharField(choices=[('any', 'Any'), ('iron', 'Iron'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('ascendant', 'Ascendant'), ('immortal', 'Immortal'), ('radiant', 'Radiant')], default='any', max_length=16),
        ),
    ]
