# Generated by Django 5.0.6 on 2026-03-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0004_lobby_country_lobby_req_cs2_faceit_lvl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='req_cs2_platform',
            field=models.CharField(blank=True, choices=[('faceit', 'Faceit'), ('premier', 'Premier'), ('fun', 'Matchmaking / Fun')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='lobby',
            name='req_dbd_role',
            field=models.CharField(choices=[('any', 'Any Role'), ('survivor', 'Survivor'), ('killer', 'Killer (Custom Game)')], default='any', max_length=16),
        ),
        migrations.AddField(
            model_name='lobby',
            name='req_eafc_mode',
            field=models.CharField(choices=[('any', 'Any Mode'), ('pro_clubs', 'Pro Clubs'), ('coop', 'Co-op Seasons')], default='any', max_length=16),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='game',
            field=models.CharField(choices=[('cs2', 'Counter-Strike 2'), ('dota2', 'Dota 2'), ('valorant', 'Valorant'), ('eafc26', 'EA Sports FC 26'), ('dbd', 'Dead by Daylight')], default='cs2', max_length=16),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='required_role',
            field=models.CharField(choices=[('any', 'Any'), ('entry', 'Entry'), ('support', 'Support'), ('igl', 'IGL'), ('awp', 'AWP / Sniper'), ('lurk', 'Lurker'), ('flex', 'Flex'), ('duelist', 'Duelist'), ('initiator', 'Initiator'), ('controller', 'Controller'), ('sentinel', 'Sentinel'), ('pos1', 'Dota Pos 1 (Carry)'), ('pos2', 'Dota Pos 2 (Mid)'), ('pos3', 'Dota Pos 3 (Offlane)'), ('pos4', 'Dota Pos 4 (Soft Support)'), ('pos5', 'Dota Pos 5 (Hard Support)'), ('striker', 'Striker / Forward'), ('midfield', 'Midfielder'), ('defender', 'Defender'), ('gk', 'Goalkeeper'), ('looper', 'Looper / Distraction'), ('gen_rusher', 'Objective / Gen Rusher'), ('healer', 'Altruistic / Healer')], default='any', max_length=16),
        ),
    ]
