# Generated by Django 5.0.6 on 2026-03-09 10:45

import django.db.models.deletion
from django.db import migrations, models

def populate_games_and_link(apps, schema_editor):
    Game = apps.get_model('lobbies', 'Game')
    Lobby = apps.get_model('lobbies', 'Lobby')
    
    # Create default games
    games_data = [
        {'slug': 'cs2', 'name': 'Counter-Strike 2', 'cover_url': 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6nx5.png'},
        {'slug': 'dota2', 'name': 'Dota 2', 'cover_url': 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5p1d.png'},
        {'slug': 'valorant', 'name': 'Valorant', 'cover_url': 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2mvt.png'},
        {'slug': 'eafc26', 'name': 'EA Sports FC 26', 'cover_url': 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6q7x.png'},
        {'slug': 'dbd', 'name': 'Dead by Daylight', 'cover_url': 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7h.png'},
    ]
    
    game_map = {}
    for data in games_data:
        game, _ = Game.objects.get_or_create(slug=data['slug'], defaults={'name': data['name'], 'cover_url': data['cover_url']})
        game_map[data['slug']] = game
        
    for lobby in Lobby.objects.all():
        old_slug = lobby.game_old
        if old_slug in game_map:
            lobby.game = game_map[old_slug]
            lobby.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0005_lobby_req_cs2_platform_lobby_req_dbd_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RenameField(
            model_name='lobby',
            old_name='game',
            new_name='game_old',
        ),
        migrations.AddField(
            model_name='lobby',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobbies', to='lobbies.game'),
        ),
        migrations.RunPython(populate_games_and_link),
        migrations.RemoveField(
            model_name='lobby',
            name='game_old',
        ),
    ]
