# Generated by Django 5.0.6 on 2026-03-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0006_game_alter_lobby_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='req_cs2_platform',
        ),
        migrations.AddField(
            model_name='lobby',
            name='play_style',
            field=models.CharField(choices=[('competitive', 'Competitive / Ranked'), ('fun', 'For Fun / Casual')], default='competitive', max_length=16),
        ),
    ]
