# Generated by Django 5.0.6 on 2026-03-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0007_remove_lobby_req_cs2_platform_lobby_play_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='req_cs2_faceit_lvl',
            new_name='req_cs2_faceit_lvl_max',
        ),
        migrations.RenameField(
            model_name='lobby',
            old_name='req_cs2_premier_rating',
            new_name='req_cs2_premier_rating_max',
        ),
        migrations.AddField(
            model_name='lobby',
            name='req_cs2_faceit_lvl_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='req_cs2_premier_rating_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
