# Generated by Django 5.0.6 on 2026-03-10 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0008_rename_req_cs2_faceit_lvl_lobby_req_cs2_faceit_lvl_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок турніру')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Зображення (URL)')),
                ('format_type', models.CharField(help_text='Наприклад: 5v5, 1v1, Double Elimination', max_length=100, verbose_name='Формат турніру')),
                ('date_time', models.DateTimeField(verbose_name='Дата та час проведення')),
                ('details', models.TextField(verbose_name='Деталі та формат')),
                ('rules', models.TextField(verbose_name='Правила')),
                ('prize', models.CharField(max_length=200, verbose_name='Приз')),
                ('contacts', models.CharField(max_length=200, verbose_name='Контакти (Discord, Telegram тощо)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='lobbies.game', verbose_name='Гра')),
            ],
            options={
                'verbose_name': 'Турнір',
                'verbose_name_plural': 'Турніри',
                'ordering': ['-date_time'],
            },
        ),
    ]
