# Generated by Django 5.0.6 on 2026-03-20 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0010_tournament_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='req_cs2_faceit_elo_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Faceit ELO'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='req_cs2_faceit_elo_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Min Faceit ELO'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='req_cs2_faceit_lvl_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='req_cs2_faceit_lvl_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
