# Generated by Django 5.0.6 on 2026-04-30 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0011_lobby_req_cs2_faceit_elo_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, verbose_name='IP сервера (напр. 192.168.1.10:27015)')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='Пароль сервера')),
                ('is_busy', models.BooleanField(default=False, verbose_name='Зайнятий зараз?')),
            ],
            options={
                'verbose_name': 'Ігровий сервер',
                'verbose_name_plural': 'Ігрові сервери',
            },
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='is_active',
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(choices=[(4, '4 команди'), (8, '8 команд'), (16, '16 команд')], default=8, verbose_name='Макс. кількість команд'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Організатор'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('registration', 'Реєстрація відкрита'), ('active', 'Турнір триває'), ('finished', 'Завершено')], default='registration', max_length=20, verbose_name='Статус турніру'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва команди')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to=settings.AUTH_USER_MODEL, verbose_name='Капітан')),
                ('players', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Гравці')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(verbose_name='Етап (Раунд)')),
                ('screenshot_proof', models.ImageField(blank=True, null=True, upload_to='tournament_proofs/', verbose_name='Скріншот результату')),
                ('status', models.CharField(choices=[('pending', 'Очікування команд'), ('ready', 'Готовий до гри (Сервер видано)'), ('conflict', '⚠️ Конфлікт результатів'), ('finished', 'Завершено')], default='pending', max_length=20, verbose_name='Статус матчу')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lobbies.match', verbose_name='Наступний матч у сітці')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lobbies.gameserver', verbose_name='Виділений сервер')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='lobbies.tournament', verbose_name='Турнір')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_team1', to='lobbies.team', verbose_name='Команда 1')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_team2', to='lobbies.team', verbose_name='Команда 2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_winner', to='lobbies.team', verbose_name='Переможець')),
            ],
            options={
                'verbose_name': 'Матч турніру',
                'verbose_name_plural': 'Матчі турнірів',
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='registered_teams',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='lobbies.team', verbose_name='Зареєстровані команди'),
        ),
    ]
