# Generated by Django 5.0.6 on 2026-05-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0012_gameserver_remove_tournament_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score_team1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рахунок Команди 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='score_team2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рахунок Команди 2'),
        ),
    ]
