# Generated by Django 5.0.6 on 2026-05-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0013_match_score_team1_match_score_team2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='organizer',
        ),
        migrations.AddField(
            model_name='tournament',
            name='match_format',
            field=models.CharField(choices=[('bo1', 'Best of 1 (Одна карта)'), ('bo3', 'Best of 3 (До 2 перемог)'), ('bo5', 'Best of 5 (До 3 перемог)')], default='bo1', max_length=10, verbose_name='Формат матчів (BO1/BO3)'),
        ),
    ]
